language: ruby
cache: bundler
rvm:
  - 2.1.9 # SLE12
  - 2.5.0 # SLE15
branches:
  only:
    - master
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - "gem install bundler"
script:
  - "bundle exec rspec --format documentation --warnings"
matrix:
  fast_finish: true
